import Home from '@components/screens/Home'
import Head from 'next/head'

import { ThirdwebSDK, ChainId } from '@thirdweb-dev/sdk';

const sdk = new ThirdwebSDK(ChainId.Mumbai);

export function getServerSideProps(ctx) {
  const { address } = ctx.params
  const contract = sdk.getNFTCollection(address);
  
  return {
    props: {
      address,
    }
  }
}

export default function SingleCollectionPage() {
  return (
    <>
      <Head>
        <title>NFT Marketplace - Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </>
  )
}
