import Home from '@components/screens/Home'
import Head from 'next/head'

export default function NewListingPage() {
  return (
    <>
      <Head>
        <title>NFT Marketplace - New Listing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </>
  )
}
